
@base_url = http://localhost:8081

###
GET {{base_url}}/ruta/list

###
GET {{base_url}}/ruta/1

###
GET {{base_url}}/ruta/1000

###
POST {{base_url}}/ruta
Content-Type: application/json

{

  "cantidad_dano": 0,
  "descripcion_dano": "Ruta segura. Es más larga, pero la caravana no sufre daño durante el viaje.",
  "ciudadOrigenId": 1,
  "ciudadDestinoId": 9,
  "ciudadOrigenNombre": null,
  "ciudadDestinoNombre": null
}

###
PUT {{base_url}}/ruta
Content-Type: application/json

{
    "id": 1,
      "cantidad_dano": 100,
  "descripcion_dano": "Ruta insegura. Hay desastres naturales en el camino.",  "ciudadOrigenId": 1,
  "ciudadDestinoId": 2,
  "ciudadOrigenNombre": null,
  "ciudadDestinoNombre": null
}

###
DELETE {{base_url}}/ruta/1
